spring:
   application:
     name: UserMS

   datasource:
     url: jdbc:mysql://localhost:3306/user
     username: root
     password: S@ffron@09p
     driver-class-name: com.mysql.cj.jdbc.Driver
   jpa: 
     hibernate:
       ddl-auto: update
     show-sql: true